name: prueba_tecnica
description: Prueba técnica

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  animation_wrappers: ^3.0.0
  global_configuration: ^2.0.0-nullsafety.1
  http: ^0.13.5
  provider: ^6.0.5
  lottie: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/

